#!/usr/bin/env bash

TAG="$(git rev-parse --short HEAD)"
NAME="$REGISTRY_NAME/$SERVICE_NAME:$TAG"

gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin $REGISTRY_NAME

gcloud config set project $GCP_PROJECT
docker push $NAME
