name: Pecosa Web Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      GCP_REGION: us-central1
      SERVICE_NAME: pecosa-server
    
    steps:
      - uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Configure Docker'
        run: gcloud auth configure-docker ${{ env.REGISTRY_NAME }}

      - name: 'Build and Push Container'
        run: |
          ./scripts/build-docker
          ./scripts/push-docker

      - name: 'Deploy to Cloud Run'
        run: |
          ./scripts/deploy-docker
          